### ISSUE TITLE
Collector program unable to fetch data for Queue Managers that has huge number of objects

### ISSUE THREAD

**Issue by atulksin** [ibm-messaging/mq-metric-samples#119]
I have been trying to use Prometheus collector sample program to collect metrics from various queue managers by connecting in client mode. It is able to collect data from most of the queue managers. However, there are few queue  managers which has multiple objects(perhaps in the range of 1000+). The collector program is unable to fetch data for such queue managers. Could you please suggest a way to overcome this situation? Is there any setting or some value that can be tweaked?

IBM MQ version : 9.2.0.1
mq_prometheus version: latest github build.

**Comment by atulksin** [comment]
I checked the queue status and it looks like the messages are being consumed very slowly by the Prometheus collector program.

AMQ8450I: Display queue status details.
   QUEUE(AMQ.626F73A42355BF02)             TYPE(QUEUE)
   CURDEPTH(39981)                         CURFSIZE(56)
   CURMAXFS(2088960)                       IPPROCS(1)
   LGETDATE(2022-05-02)                    LGETTIME(06.41.15)
   LPUTDATE(2022-05-02)                    LPUTTIME(06.41.14)
   MEDIALOG( )                             MONQ(MEDIUM)
   MSGAGE(115)                             OPPROCS(0)
   QTIME(115128858, 115186960)             UNCOM(NO)

**Comment by atulksin** [comment]
I'm getting 2033. This is what I get when I enabled trace.

TRAC[0103] > [parsePCFResponse]
TRAC[0103] < [parsePCFResponse] rp: 0
TRAC[0103] > [getMessage]
TRAC[0103] > [getMessageWithHObj]
TRAC[0103] < [getMessageWithHObj] rp: 0 Error: MQGET: MQCC = MQCC_FAILED [2] MQRC = MQRC_NO_MSG_AVAILABLE [2033]
TRAC[0103] < [getMessage] rp: 0 Error: MQGET: MQCC = MQCC_FAILED [2] MQRC = MQRC_NO_MSG_AVAILABLE [2033]
TRAC[0103] < [ProcessPublications] rp: 0
DEBU[0103] Collected and processed resource publications successfully
DEBU[0103] Skipping poll for object status
DEBU[0103] Doing queue rediscovery
TRAC[0103] > [RediscoverAndSubscribe]
TRAC[0103] > [discoverAndSubscribe]
TRAC[0103] > [discoverQueues]
TRAC[0103] > [inquireObjects] : Type: 1 Patterns: *
TRAC[0103] > [statusClearReplyQ]
TRAC[0103] < [statusClearReplyQ] rp: 0
TRAC[0103] > [getWithoutTruncation]
TRAC[0103] getWithoutTruncation: Trying MQGET with buffer size 65536
TRAC[0103] < [getWithoutTruncation] rp: 0
TRAC[0103] Received response of type 2 [MQCFT_RESPONSE] and length 49112
TRAC[0103] Number of returned strings = 943
TRAC[0103] < [inquireObjects] rp: 0 Error: nil
TRAC[0103] < [discoverQueues] rp: 0 Error: nil
TRAC[0103] > [createSubscriptions]
TRAC[0103] < [createSubscriptions] rp: 0 Error: nil
TRAC[0103] < [discoverAndSubscribe] rp: 0 Error: nil
TRAC[0103] < [RediscoverAndSubscribe] rp: 0 Error: nil
TRAC[0103] > [RediscoverAttributes]
TRAC[0103] > [inquireChannelAttributes]
TRAC[0103] > [statusClearReplyQ]
TRAC[0103] < [statusClearReplyQ] rp: 0
TRAC[0103] < [inquireChannelAttributes] rp: 1 Error: nil
TRAC[0103] < [RediscoverAttributes] rp: 0 Error: nil
DEBU[0103] Reporting gauge for mqput_bytes
DEBU[0103] Reporting gauge for mqput1_non_persistent_message_count
DEBU[0103] Reporting gauge for non_persistent_bytes

**Comment by ibmmqmet** [comment]
Dealing with 1000 objects is not inherently a problem - systems and queue managers usually run fast enough that the collector can get that number of messages fairly rapidly, particularly as the messages are usually non-persistent. If you really have slow retrieval from the queue holding the publications then perhaps there's something else going on. Though it might depend on the `scrape_interval`, how many publications accrue before they are being read.

When I was trying to run the prometheus collector on a local machine, while collecting metrics from a qmgr on the other side of the atlantic, one thing I changed was the prometheus `scrape_interval` for that particular collector. So instead of a typical 15s, I set it to 2m, giving enough time to process all the messages before the next collection tried to start. I also extended the pollInterval in the collector's configuration so that the DISPLAY xxSTATUS operations were not done as frequently. 

All of that became unnecessary when I put the collector much closer to the qmgr (on the same hardware), so the long distance was between prometheus and the collector rather than between the collector and the qmgr.

It might be interesting to tune the qmgr resource publication frequency to match the `scrape_interval` if there really is an issue processing them all in time. See https://community.ibm.com/community/user/communities/community-home/librarydocuments/viewdocument?DocumentKey=827fe508-893a-4afb-b425-55a2e1ac5665 with the `MonitorPublishHeartBeat` attribute.

Getting a 2033 response in the trace is not necessarily a problem, as it will often simply indicate that the last message really has been processed - from the trace you're showing, that would likely be the resource publications rather than the STATUS query replies.

**Comment by atulksin** [comment]
Thanks a lot @ibmmqmet for your suggestions. I was able to get this fixed by increasing the `MonitorPublishHeartBeat` attribute. It was working with default value as well when running the collector on the same machine as that of Queue Manager.
