### ISSUE TITLE
Build in z/OS

### ISSUE THREAD

**Issue by AlexAlvesJr** [ibm-messaging/mq-metric-samples#134]
Hey, Mark! How are you?

We want to build the exporter to monitor our QMGRs in z/OS. 
Just to confirm, even in Linux (Open/Distributed) or Linux for Z is the method to build the exporter the same (as described in the section "Building a component")?

Other question: do you know if this exporter have been already tested/deployed in zCX?

Thanks for your attention.

Kind regards,
Alex

**Comment by ibmmqmet** [comment]
These days I mostly use the files from the `scripts` directory - usually `buildMonitors.sh` to compile the programs using Docker containers rather than doing it by hand. The README instructions look like they need a bit of updating, but should still basically work for all the distributed platforms including zLinux. 

Building natively on z/OS is not something that works, though I know a couple of people are interested in trying to work out the necessary changes.

I've build and run the collectors on a real zLinux image, connected as a client to z/OS qmgrs on the same physical machine. I don't know of any reason why it couldn't be put into a zCX container instead, but I've not heard from anyone who's actually done it.

**Comment by AlexAlvesJr** [comment]
Ok, Mark! I appreciate your help.
