### ISSUE TITLE
Support monitoring of queue statistics

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-metric-samples#136]
It would be great if we could get the LAST PUT TIME, LAST GET TIME, IPPROCS, OPPROCS metrics for a given local queue as this is a very common use case in MQ operations.

**Comment by abudavis** [comment]
The _ibmmq_queue_input_handles & ibmmq_queue_output_handles_ does show the IPPROCS & OPPROCS, but we are still missing the LPUTDATE, LPUTTIME, LGETDATE & LGETTIME statistics, any ideas?

Example queue statistics from the "dis qs" command:
---
dis qs(DUMMY)
 Display queue status details.
   QUEUE(DUMMY)     TYPE(QUEUE)
   CURDEPTH(0)                             CURFSIZE(1)
   CURMAXFS(2088960)                       IPPROCS(1)
   LGETDATE(2022-06-14)                    LGETTIME(13.39.18)
   LPUTDATE(2022-06-14)                    LPUTTIME(13.39.17)
   MEDIALOG( )                             MONQ(HIGH)
   MSGAGE(0)                               OPPROCS(2)
   QTIME(281796, 359344)                   UNCOM(NO)
---

NOTE: ibmmq_queue_time_since_put/get is for QTIME

**Comment by ibmmqmet** [comment]
What makes you think they are for QTIME? They are not. They are, as named, the time since the last operation. Turned into integers of course, so they can be used as metrics, but still taken from those fields. As you can verify in the source code. There are separate metrics for the QTIME_SHORT/LONG values.

**Comment by abudavis** [comment]
That was my bad :( 
Thank you!
