### ISSUE TITLE
DESCR file in metrics 

### ISSUE THREAD

**Issue by piotrekbed** [ibm-messaging/mq-metric-samples#16]
Hi,
Is any chance to metrics return DESCR field and USAGE (for the queues).  

BR
Piotrek

**Comment by ibmmqmet** [comment]
DESCRIPTION is not a metric. As it's a string, the only way to have it passed to prometheus would be to add it as a label to the object but I'd rather not do that - the more labels on an entry in prometheus, the harder it has to work. 

There's also danger of over-extending the capabilities of these monitors - why that attribute and not all the others from an object. (Although it is a config attribute I added MAXDEPTH as a metric to enable calculations rather than as an object descriptor/selector.)

I'm a bit more sympathetic to adding USAGE to allow graphs of transmission queues to be selected, but that does have similar attribute-vs-metric considerations. 

A better approach might be to have a separate view in grafana that is selecting configuration attributes from another datasource. It's fairly easy, for example, to have Grafana extract information from MySQL tables that might be populated with your reasonably-static queue manager configuration.

**Comment by ibmmqmet** [comment]
v4.0.8 now has USAGE as a label on queue objects

**Comment by keithknott26** [comment]
By the way I came across this project and I was also looking for the DESCR() feature , the use case was to pass applicationName (which is currently in the (CHANNEL and QUEUE DESCR() fields) and use that as a label to prometheus so we could use it while filtering. Being able to have DESCR() will allow us to map channel and queue names directly to a applicationName using the built in MQ fields.

Is this reasonably straight forward to add? I see that you can't retrieve DESCR() directly it would have to be "looked up" and written as a channel and queue attribute. Perhaps I'll have a look at the MAXDEPTH() implementation and that will give me some ideas.

**Comment by ibmmqmet** [comment]
The most recent restructure of the code, where it's now doing a DISPLAY CHL to get some numeric attributes,  makes it more feasible to add DESCR. I'll take another look at it next time I'm doing some updates.

**Comment by keithknott26** [comment]
That's great news, thanks very much!
