### ISSUE TITLE
Want to use Prometheus to monitor DR/HA RDQM status

### ISSUE THREAD

**Issue by Boymmx** [ibm-messaging/mq-metric-samples#166]
Want to use prometheus to monitor DR/DA RDQM status

as shown in "rdqmstatus -m <qmname>" command.

**Comment by ibmmqmet** [comment]
I took a look at whether this could be done, but it's really not feasible within the scope of this package.
* rdqmstatus does not have a programmatic equivalent
* it requires direct access to the command line to execute (which means setting up something like SSH for remote collectors)
* the output is text and not easily parsable
* the output is nearly all status information, not metrics so that doesn't fit very well 

Dealing with all of these items would essentially require a completely different collector and configuration mechanism. Therefore it's not something I'm going to consider further for this repo.

I would consider adding further metrics that might be available in the output of the DISPLAY QMSTATUS command; you might like to open an Idea against the base MQ product to get that command extended.

**Comment by kriahna-22** [comment]
rdqmstatus -n
rdqmstatus -m QMNAME for perticular queue manager
