### ISSUE TITLE
Best approach on multiple QMGRs

### ISSUE THREAD

**Issue by maurochss** [ibm-messaging/mq-metric-samples#181]
Hi all,

What is the best approach case you have multiple QMGRs on the same host. About 30 :)

I modified mq_prometheus.sh to source a "settings file" named "mq_prometheus.qmgrname" which as the following settings:

------ FILE for mq_prometheus.qmgr1"
IBMMQ_PROMETHEUS_HOST=binding_ip_address
IBMMQ_PROMETHEUS_PORT=9157
queues=QAPP1.* QAPP2.*
channels=QMGR1_SVR_CHL

------ FILE for mq_prometheus.qmgr2"
IBMMQ_PROMETHEUS_HOST=binding_ip_address
IBMMQ_PROMETHEUS_PORT=9158
queues=QIN1.* QIN2.*
channels=QMGR2_SVR_CHL

So there is a file like that per QMGR. Is there any other approach?

--
Regards,
Mauro Chan Son Suleimane

**Comment by ibmmqmet** [comment]
There are probably variations in exactly how you write a startup script, with a combination of environment variables that vary by qmgr, and an otherwise common file for the rest of the attributes. And if things are predictable like QM1 uses port 1414, QM2 uses 1415 etc, then you might be able to use arithmetic to calculate values instead of explicitly hardcoding them. But all that will depend on your environment. 

But the basic idea of independent configurations is correct.
