### ISSUE TITLE
Client Connections

### ISSUE THREAD

**Issue by usuresh80** [ibm-messaging/mq-metric-samples#31]
Trying to use mq_prometheus  exporter , But I want to connect to remote QMGR through Server connection channel to monitor MQ, Can I  compile  your source  code as is to make it work  to create exporter ?

**Comment by kidharb** [comment]
> Trying to use mq_prometheus exporter , But I want to connect to remote QMGR through Server connection channel to monitor MQ, Can I compile your source code as is to make it work to create exporter ?

Yes you can, I did last week and it is working great.
Just remember to set the ARGS="$ARGS -ibmmq.client=true" parameter and populate the MQSERVER environment variable.

**Comment by usuresh80** [comment]
Thanks  you , Do I need to compile Prometheus exporter file  - "mq_prometheus" again or readily available for download from github ?

**Comment by kidharb** [comment]
You cannot download it from Github.
And if you could, I would still advise you to compile from source, so that if you have any issues you can fix them, test them and contribute to this project. 

All you need to do is install the Go compiler and follow the compilation instructions in this projects readme.
