### ISSUE TITLE
Understanding ibmmq_queue_mqget_count value

### ISSUE THREAD

**Issue by daveram** [ibm-messaging/mq-metric-samples#333]
Well hello there!  We're using mq_prometheus to scrape a queue manager and present a grafana dashboard that shows the number of get operations in the last hour

What is the value of ibmmq_queue_mqget_count representing?  The number of get operations since the last scrape?  Or is it the number of currently running gets, or something else?

I kind've expected this to be a counter instead of a gauge showing the increasing total of get operations so we could use rate() in promql.  Unclear on what this metric is reporting in terms of values, any light you can shed on it would be great!

**Comment by ibmmqmet** [comment]
The value is the number of GETs in the last collection interval.

For historic reasons, all values are given as gauges - changing that default would likely break existing dashboards. Most of the metrics are provided from the queue manager as deltas across the interval, rather than absolute values.

But there is an undocumented option in the current version that switches to using Counters for relevant metrics that you might like to try in the config file:

```
prometheus:
   overrideCType: true
```
I've not done much testing with it yet (hence the lack of docs), but it does allow the `rate()` operation.

**Comment by daveram** [comment]
Thanks this helps a lot!  We'll stick with the current setup for now but good to know there's an option to go with counters.  This question was primarily driven by confusion around the timeframe of the values that didn't line up with other instrumentation we were comparing to, and now also answers what we're storing in the reply queue should the scrapes fail (the deltas!)

**Comment by brian-heady** [comment]
I'm using the prometheus datasource in grafnana, and I'm trying to count the total number of messages leaving a specific queue.

When I try `increase(ibmmq_queue_destructive_mqget_persistent_message_count{queue=~".*QUEUE.*"}[$__range])`, I get a return of 407399 for one day and 967287 for the next. Then, when I move the range to encompass the two days, I get a range total of 1280991.  This doesn't seem consistent.  The data goes even further out of alignment the further I go out in time.  I should be getting a count of around 4-5 million messages leaving the queue (per application logs)

I've looked in the sample dashboards (MQ Prometheus) provided and do see where I can get the qmgr total count of messages, that's helpful but not exactly what I was looking for since it gives point in time and not a sum of all the messages.
``
I have usePublications true set in my (attached) config

I'm intrigued by this prometheus override:
prometheus:
   overrideCType: true

Will this get me an exact count of messages in a queue?  

Otherwise, is there a grafana query you might recommend?
[mq_prometheus.pdf](https://github.com/user-attachments/files/18323407/mq_prometheus.pdf)

**Comment by ibmmqmet** [comment]
I'd suggest setting that `overrideCType` option to true. It looks like `increase` is meant to work with Counters, which is what you'll have with that option.
