### ISSUE TITLE
Support for MQ Active/Standby Mode

### ISSUE THREAD

**Issue by BoLB23** [ibm-messaging/mq-metric-samples#35]
We have a 2 node MQ Cluster - one node is primary (active), one node is secondary (standby). MQ is started with the -x flag so whichever cluster comes up first registers as primary, second one as secondary. Failover is automatic if the listener ever crashes on the primary node.

MQ exporter does not seem to support this, as it will start on whichever node is primary, but whichever node is secondary will continuously crash when started as a systemd process. 

Should the exporter check if the node is registered as standby and if so should it not crash loop and instead provide some metric saying it is in standby mode?

**Comment by ibmmqmet** [comment]
A failure to connect is immediately fatal, before any work is done to make the exporter visible to Prometheus invocations so you can tell that something has failed from the main Prometheus status panels for endpoints. 

What I am thinking of doing is making the specific reason for the connection failure more visible. For example, if the connection to the qmgr fails with MQRC_STANDBY_Q_MGR, then exiting with a particular return code. (I can't use the actual MQRC value as the exit code from a program because they are >255.) That would allow any startup script to choose how to handle the error including looping until the standby becomes primary.

Restructuring the code so that it did something special for that one particular error code, and continuing to loop and to try to reconnect would be an awkward change as so much of the configuration needs to be validated by connecting to a qmgr up front - it's not good to delay error checking like "have you given a valid replyq name" until some arbitrary later time.

**Comment by ibmmqmet** [comment]
The v5.0.0 release includes a specific exit code for when connection has been tried to a standby qmgr so that startup scripts can detect it and retry.
