### ISSUE TITLE
Channel metrics

### ISSUE THREAD

**Issue by salapat11** [ibm-messaging/mq-metric-samples#44]
We have ~7000 active channel connections on some queue managers.  The exporter is timing out after 120 seconds on some scrapes.  Found these messages in the logs - MQRC_NO_MSG_AVAILABLE [2033].

Any ideas how to fix this?

**Comment by salapat11** [comment]
Mark, any thoughts?

**Comment by ibmmqmet** [comment]
2 minutes seems a very long time to collect status, especially as the channel status is collected in batches using wildcards. Is there a slow network between the collector and the qmgr. The only time I saw anything comparable, I had 4000 miles between components, and dealt with it by putting the collector in an LPAR alongside the qmgr so the 4000 miles was between prometheus and the collector rather than between the collector and the qmgr. 

There is a 3 second timeout for getting each reply message (function statusGetReply - that's in between each message, not a total time for the entire set of responses) and if things are running very slowly, then perhaps that would show a 2033 though I thought that 2033 specifically would not get logged.

One thing I'm adding for the next version is a Trace logging level that tracks a lot more detail of the flow and might be able to give a better diagnosis

**Comment by salapat11** [comment]
Collector and queue manager are in the same data center, so not too far.  I have a "*" for channel pattern to collect all the channel statuses.  Does it help if the pattern is split?

**Comment by ibmmqmet** [comment]
I wouldn't expect splitting to help, But it might be worth trying. I think I can now see where the 2033 is getting logged from, but it then suggests either a very slow response from the qmgr. One other possibility is that the replyq derived from the modelq is getting full so that returned status messages are getting discarded. If it's the latter, then splitting patterns could help.
