### ISSUE TITLE
metricset not loading

### ISSUE THREAD

**Issue by HamHamTime** [ibm-messaging/mq-metric-samples#54]
Hello,

Do you know where the qmgr metricset is loaded? The fieldnames I am getting are different:

prometheus.metrics.ibmmq_qmgr_non_persistent_message_browse_count as oppose to
prometheus.metrics.ibmmq_qmgr_non_persistent_message_browse_total  

Thanks,

**Comment by ibmmqmet** [comment]
I don't understand what you are asking. You say "different" but don't say what where you get the _total name from.

**Comment by HamHamTime** [comment]
I configured Metricbeat 7.9.2 and enabled the IBM-MQ Metricbeat module. When I check the documentation their metricset(qmgr) shows all of the fields ending with _total. I also checked the module's dashboard for Kibana are using the same fields. Right now the dashboards don't show any values because the configured name is different.

https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-ibmmq-qmgr.html#metricbeat-metricset-ibmmq-qmgr

Thanks for your quick replies!

**Comment by ibmmqmet** [comment]
This package is not directly related to the MetricBeat solution. That package appears to building on, and documented, assuming the use of, the metric collector in the [mq-container](https://github.com/ibm-messaging/mq-container) image which (although it in turn was based on an very early version of this repo) uses a different approach for creating the full metric names, based on the descriptions provided by the queue manager subscription metadata - what comes out of the qmgr is not directly usable as a metric name for various reasons. 

So it's not surprising to see slightly different metric names as there are slightly different heuristics.

You can see how this package reformats the name in [the source file](https://github.com/ibm-messaging/mq-metric-samples/blob/master/vendor/github.com/ibm-messaging/mq-golang/v5/mqmetric/discover.go) at the `formatDescription` function.

That means the collectors here will often have a `_count` suffix instead of a `_total`. Any imported dashboards should be easily modifiable to pick up the different metric names.

**Comment by ibmmqmet** [comment]
Closing as answered
