### ISSUE TITLE
Exporter Not Running when QM is stopped

### ISSUE THREAD

**Issue by sudhir-maurya** [ibm-messaging/mq-metric-samples#67]
I am running the MQ Prometheus Exporter using the below command:

`./mq_prometheus -ibmmq.queueManager=QM1 -ibmmq.monitoredQueues="E.*" -ibmmq.monitoredChannels="CHANNEL-1" -ibmmq.resetQStats=true`

Exporter running fine by passing the appropriate argument. But when I stop the Queue Manager to test the status of Queue Manager, exporter is going down with it. Expected should be to tell the status of Queue Manger as in Not Running state or the value to 0 . Just like when I stop the local queue it shows the status Not Running.

**Comment by ibmmqmet** [comment]
The code deliberately, currently, does not attempt to do reconnections to a failed queue manager. In many cases people are running the collector as a service, so it is automatically restarted along with the qmgr. But doing reconnection in the collector itself has complications - particularly with prometheus as opposed to the other collectors - because of the pull model of gathering metrics. It's something I might look at again in future, but it's not in immediate plans. 

The usual recommendation for continual running of the collector is to wrap it in a script that restarts it regularly if necessary. And of course, the lack of a specific connection metric (it'll be empty/null) in a time period can be taken in imply that the qmgr is not running.

**Comment by harish225n** [comment]
run it with the shell script ./mq_prometheus.sh as mentioned below. Script is available in the folder.

./mq_prometheus.sh QUEUE_MANAGER 9157 &
