### ISSUE TITLE
Howto: code stub to create additional calculations?

### ISSUE THREAD

**Issue by z5d69** [ibm-messaging/mq-metric-samples#80]
Really appreciate this repository.  We have a handful of calculated metrics that we'd like to export however would like to avoid unmaintainable forks / separate repositories / etc. of the code.  Our monitoring solution doesn't have the capability to perform these calculations (yes, we checked with the vendor).  

One such calculated example is a queue depth percent (ibmmq_queue_depth/ibmmq_queue_attribute_max_depth?  Or something similar?  Is there a way to add this or provide a file where any custom calculations could reside?

**Comment by ibmmqmet** [comment]
There's no real way to add your own metrics other than modifying the code. It's not something I'd plan to do for several reasons:
* Some numbers like CurrentDepth that come from qmgr resource publications are not explicitly known to this package (actually the mqmetric package) so there's no convenient place to insert modifications or calculations. Those metrics are passed on essentially unprocessed through the collection APIs.
* Other values are collected on different schedules and may not be available on a given iteration
* The idea of creating some external interface for arbitrary calculations feels very inappropriate. 

This kind of thing really should be the job of the metrics processor rather than the raw collector. Which tool are you using - maybe there's an alternative approach

**Comment by z5d69** [comment]
Dynatrace is the vendor being used for monitoring.  Our feedback from Dynatrace was that calculations spanning metrics were unavailable (A+B, A-B, A/B, etc.).  It sounded like metrics couldn't be correlated with each other (although they can be analyzed via dimensions, etc.).  I thought this was odd but could only ask about this functionality so many way.

**Comment by ibmmqmet** [comment]
https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v2/metric-expressions/ suggests that there are ways to return values that combine metrics but it might depend on exactly how you're accessing them.

**Comment by z5d69** [comment]
Thank you for the research!  Our access doesn't extend to Dynatrace, only to the MQ / MQ Metrics implementation (which is why I was looking for an approach using MQ Metrics instead of Dynatrace).  It's probable that this functionality only exists through the API and not exposed through the UI.  I'll ask the monitoring team why the API wouldn't work.
