### ISSUE TITLE
Required to get queue/channel level metrics?

### ISSUE THREAD

**Issue by irl-segfault** [ibm-messaging/mq-metric-samples#81]
Hi!

I've got an MQ pod running in Kubernetes, deployed via the [official Helm chart](https://github.com/IBM/charts/tree/master/stable/ibm-mqadvanced-server-dev).  By default, this configures the MQ pod to expose a metrics port at 9157, and a Service to access this.  There are many Prometheus metrics exposed here, but notably lacking and metrics at the queue/channel level -- only higher level manager metrics.

My question is -- is the code here in `mq-metrics-samples` required to obtain more granular metrics (such as queue depth) or is there a way to configure the MQ instance itself to expose those natively.  Seems odd that MQ would by default expose a set of metrics out-of-the-box, but require another set of tooling to go deeper.

Hopefully this makes sense and you can see why I'm a little confused.  Thanks in advance!

**Comment by ibmmqmet** [comment]
Yes you need something like this package, or another (probably commercial) tool, to get at the more detailed level of statistics and status that the queue manager can provide. 

The collector that is build into the standard container image, which was based on a very early version of this code, can only extract the qmgr-level information. This package has gone a long way forward since that fork was taken.

**Comment by irl-segfault** [comment]
Thanks!  What would it take to integrate this implementation as the default collector/exporter in the mainline image?  Seems like that would make a lot of sense to do.  Thoughts?

**Comment by ibmmqmet** [comment]
I know that the team have already heard requests for enhancements to the default monitoring options in the image, but it doesn't hurt to raise it again. You could open a formal product enhancement request (Idea) at https://integration-development.ideas.ibm.com/ or raise an issue at https://github.com/ibm-messaging/mq-container/issues
